
FROM amazonlinux:2

# Set working directory
WORKDIR /usr/src/app

# Install Node.js and other dependencies
RUN curl -fsSL https://rpm.nodesource.com/setup_16.x | bash - && \
    yum install -y nodejs && \
    yum clean all

# Copy application files
COPY package.json ./
COPY index.js ./

# Install Node.js dependencies
RUN npm install

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]

